# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(884, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox_year = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_year.setMinimum(2000)
        self.spinBox_year.setMaximum(2100)
        self.spinBox_year.setObjectName("spinBox_year")
        self.horizontalLayout.addWidget(self.spinBox_year)
        self.line_4 = QtWidgets.QFrame(self.groupBox)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout.addWidget(self.line_4)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_month = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_month.setObjectName("comboBox_month")
        self.horizontalLayout.addWidget(self.comboBox_month)
        self.line_5 = QtWidgets.QFrame(self.groupBox)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout.addWidget(self.line_5)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_regcode = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_regcode.setObjectName("comboBox_regcode")
        self.horizontalLayout.addWidget(self.comboBox_regcode)
        self.line_6 = QtWidgets.QFrame(self.groupBox)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout.addWidget(self.line_6)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_dtp_count = QtWidgets.QLabel(self.groupBox_2)
        self.label_dtp_count.setObjectName("label_dtp_count")
        self.horizontalLayout_2.addWidget(self.label_dtp_count)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.label_dead = QtWidgets.QLabel(self.groupBox_2)
        self.label_dead.setObjectName("label_dead")
        self.horizontalLayout_2.addWidget(self.label_dead)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_inj = QtWidgets.QLabel(self.groupBox_2)
        self.label_inj.setObjectName("label_inj")
        self.horizontalLayout_2.addWidget(self.label_inj)
        self.line_3 = QtWidgets.QFrame(self.groupBox_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_2.addWidget(self.line_3)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_proc = QtWidgets.QLabel(self.groupBox_2)
        self.label_proc.setObjectName("label_proc")
        self.horizontalLayout_2.addWidget(self.label_proc)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_graph = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_graph.setTitle("")
        self.groupBox_graph.setObjectName("groupBox_graph")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_graph)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_graph = QtWidgets.QVBoxLayout()
        self.verticalLayout_graph.setObjectName("verticalLayout_graph")
        self.horizontalLayout_3.addLayout(self.verticalLayout_graph)
        self.verticalLayout_5.addWidget(self.groupBox_graph)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 884, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menu_Service = QtWidgets.QMenu(self.menubar)
        self.menu_Service.setObjectName("menu_Service")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Qt = QtWidgets.QAction(MainWindow)
        self.action_Qt.setObjectName("action_Qt")
        self.action_reload_regcodes = QtWidgets.QAction(MainWindow)
        self.action_reload_regcodes.setObjectName("action_reload_regcodes")
        self.action_Start = QtWidgets.QAction(MainWindow)
        self.action_Start.setObjectName("action_Start")
        self.menu_File.addAction(self.action_Exit)
        self.menu_Help.addAction(self.action_About)
        self.menu_Help.addAction(self.action_Qt)
        self.menu_Service.addAction(self.action_Start)
        self.menu_Service.addAction(self.action_reload_regcodes)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Service.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.action_Exit.triggered.connect(MainWindow.close)
        self.action_About.triggered.connect(MainWindow.show_about_window)
        self.action_Qt.triggered.connect(MainWindow.show_aboutqt_window)
        self.pushButton.clicked.connect(MainWindow.start_calculation)
        self.action_reload_regcodes.triggered.connect(MainWindow.update_codes)
        self.action_Start.triggered.connect(MainWindow.start_calculation)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.spinBox_year, self.comboBox_month)
        MainWindow.setTabOrder(self.comboBox_month, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Парсер сайта статистики ГИБДД"))
        self.groupBox.setTitle(_translate("MainWindow", "Исходные данные"))
        self.label.setText(_translate("MainWindow", "Год"))
        self.label_2.setText(_translate("MainWindow", "Месяц"))
        self.label_3.setText(_translate("MainWindow", "Регион"))
        self.pushButton.setText(_translate("MainWindow", "Запустить парсер"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Статистика"))
        self.label_4.setText(_translate("MainWindow", "ДТП всего"))
        self.label_dtp_count.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Число погибших"))
        self.label_dead.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Число раненых"))
        self.label_inj.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "Степень тяжести последствий"))
        self.label_proc.setText(_translate("MainWindow", "0.00%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Исходные данные и статистика"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Графики"))
        self.menu_File.setTitle(_translate("MainWindow", "Файл"))
        self.menu_Help.setTitle(_translate("MainWindow", "Справка"))
        self.menu_Service.setTitle(_translate("MainWindow", "Сервис"))
        self.action_Exit.setText(_translate("MainWindow", "Выход"))
        self.action_About.setText(_translate("MainWindow", "О программе"))
        self.action_Qt.setText(_translate("MainWindow", "Версия Qt"))
        self.action_reload_regcodes.setText(_translate("MainWindow", "Обновить справочник кодов регионов"))
        self.action_Start.setText(_translate("MainWindow", "Запустить парсер"))

